apiVersion: apps/v1
kind: Deployment

metadata:
  name: securecart-backend
  labels:
    app: securecart
    component: backend

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: securecart
      component: backend

  template:
    metadata:
      labels:
        app: securecart
        component: backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          env:
            - name: APP_NAME
              value: "SecureCart Backend"

            - name: API_VERSION
              value: "0.1.0"

            - name: ENVIRONMENT
              value: {{ .Values.global.environment | quote }}

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: DB_HOST
              value: "securecart-postgres"

            - name: DB_PORT
              value: {{ .Values.postgres.service.port | quote }}

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: POSTGRES_DB

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret }}
                  key: POSTGRES_PASSWORD

          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
{{ toYaml .Values.backend.resources | indent 12 }}