apiVersion: v1
kind: Service

metadata:
  name: securecart-postgres

spec:
  clusterIP: None

  selector:
    app: securecart
    component: database

  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.containerPort }}