apiVersion: batch/v1
kind: Job
metadata:
  name: securecart-db-migration
  labels:
    app: securecart
    component: database-migration

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: securecart
        component: database-migration

    spec:
      restartPolicy: Never

      containers:
        - name: migration
          image: ghcr.io/greatone33/securecart-backend:0.4.1
          imagePullPolicy: Always

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          command:
            - /bin/sh
            - -c

          args:
            - |
              set -e
              alembic upgrade head
              python seed.py

          env:
            - name: DB_HOST
              value: "securecart-postgres"

            - name: DB_PORT
              value: "5432"

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: securecart-postgres-secret
                  key: POSTGRES_DB

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: securecart-postgres-secret
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: securecart-postgres-secret
                  key: POSTGRES_PASSWORD
