apiVersion: apps/v1
kind: Deployment

metadata:
  name: securecart-frontend
  labels:
    app: securecart

spec:
  replicas: 3

  selector:
    matchLabels:
      app: securecart
      component: frontend

  template:
    metadata:
      labels:
        app: securecart
        component: frontend

    spec:
      containers:
        - name: frontend
          image: ghcr.io/greatone33/securecart-frontend:0.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: securecart-config
                  key: APP_NAME

            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: securecart-config
                  key: ENVIRONMENT

            - name: VERSION
              valueFrom:
                configMapKeyRef:
                  name: securecart-config
                  key: VERSION

            - name: COMPANY
              valueFrom:
                configMapKeyRef:
                  name: securecart-config
                  key: COMPANY

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: BACKEND_HOST
              value: "securecart-backend-service"

            - name: BACKEND_PORT
              value: "8000"

          startupProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: frontend-tmp
              mountPath: /tmp

      volumes:
        - name: frontend-tmp
          emptyDir: {}