apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: securecart-ingress
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  
spec: 
  ingressClassName: nginx 

  tls: 
    - hosts: 
        - securecart.local
      secretName: securecart-tls

  rules: 
    - host: securecart.local
      http: 
        paths: 
          - path: /
            pathType: Prefix
            backend: 
              service: 
                name: securecart-service
                port: 
                  number: 80