apiVersion: apps/v1
kind: Deployment
metadata:
  name: securecart-frontend
  labels:
    app: securecart
spec:
  replicas: 3

  selector:
    matchLabels:
      app: securecart
      component: frontend

  template:
    metadata:
      labels:
        app: securecart
        component: frontend

    spec:
      initContainers:
        - name: render-frontend
          image: nginx:1.27-alpine

          command:
            - /bin/sh
            - -c

          args:
            - |
              envsubst '${APP_NAME} ${ENVIRONMENT} ${VERSION} ${COMPANY} ${POD_NAME}' \
                < /templates/index.html.template \
                > /generated/index.html

          envFrom:
            - configMapRef:
                name: securecart-config

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: frontend-template
              mountPath: /templates

            - name: generated-content
              mountPath: /generated

      containers:
        - name: frontend
          image: nginx:1.27-alpine

          ports:
            - containerPort: 80

          envFrom:
            - configMapRef:
                name: securecart-config

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          volumeMounts:
            - name: generated-content
              mountPath: /usr/share/nginx/html

      volumes:
        - name: frontend-template
          configMap:
            name: securecart-frontend-content

        - name: generated-content
          emptyDir: {}